// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductApi;

#nullable disable

namespace CoffeApi.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20231210120602_InitCoffes")]
    partial class InitCoffes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProductLib.Coffe", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("Id");

                    b.Property<byte>("Category")
                        .HasColumnType("tinyint")
                        .HasColumnName("Category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<double?>("Price")
                        .HasColumnType("float")
                        .HasColumnName("Price");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "841cbc9e-cb95-4b4c-b2c0-cb7b3d64441d",
                            Category = (byte)1,
                            Code = "CffD001",
                            CreatedOn = new DateTime(2023, 12, 10, 19, 6, 2, 561, DateTimeKind.Local).AddTicks(8408),
                            Name = "Moca"
                        },
                        new
                        {
                            Id = "a42df353-757f-4611-9261-eeab6e2e45ac",
                            Category = (byte)2,
                            Code = "CFFD002",
                            CreatedOn = new DateTime(2023, 12, 10, 19, 6, 2, 561, DateTimeKind.Local).AddTicks(8431),
                            Name = "Capucino"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
